name: "Ut"
description: "Portfolio and Blog of Uttam Grandhi"

url: "http://localhost:4000"
#You do not need to surround a string with quotation marks unless it contains specific characters, like the colon (":")

#paginate: 10

markdown: rdiscount
permalink: pretty
pygments: true
safe: true
lsi: false


