name: "Uttam Grandhi"
description: "Portfolio and Blog of Uttam Grandhi"
url: "http://utt.am"

assetURL: "http://utt.am"
#You do not need to surround a string with quotation marks unless it contains specific characters, like the colon (":")

#paginate: 10

markdown: rdiscount
permalink: pretty
highlighter: pygments
safe: true
lsi: false
gems: 
 - jekyll-gist


